version: '3.9'
services:
  tattoo:
    build: ./tattoo
    command: bash -c "python manage.py migrate && python manage.py create_data && python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:8080 --workers 1"
    volumes:
      - ./tattoo:/tattoo
      - static:/tattoo/staticfiles
      - media:/tattoo/media
    env_file:
      - tattoo/.env
    ports:
      - 8080:8080
    expose:
      - "8080"