# Generated by Django 5.0.6 on 2024-05-28 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_setting', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Slider/', verbose_name='Картинка')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отоброжать')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
        migrations.CreateModel(
            name='TattooType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип тату')),
            ],
            options={
                'verbose_name': 'Тип тату',
                'verbose_name_plural': 'Типы тату',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='WorksPhoto/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('type', models.CharField(max_length=30, verbose_name='Тип тату')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='MastersPhoto/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Стаж работы')),
                ('education', models.CharField(blank=True, max_length=100, verbose_name='Образование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отоброжать')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_setting.salon', verbose_name='Салон')),
                ('tattoo_type', models.ManyToManyField(blank=True, to='database.tattootype', verbose_name='Типы тату')),
                ('works', models.ManyToManyField(blank=True, to='database.works', verbose_name='Работы мастера')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.master')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальный')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('icon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='site_setting.socialaccounticon')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_account', to='database.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
