# Generated by Django 5.0.6 on 2024-05-29 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='user',
            field=models.OneToOneField(blank=True, default=11, on_delete=django.db.models.deletion.CASCADE, related_name='user_master', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
