# Generated by Django 5.0.6 on 2024-05-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_master_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Стаж работы'),
        ),
        migrations.AlterField(
            model_name='master',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Отоброжать'),
        ),
    ]
