# Generated by Django 5.0.6 on 2024-06-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_consultation_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
