# Generated by Django 5.0.6 on 2024-05-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_master_experience_alter_master_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='tattoo_type',
            field=models.CharField(default=1, max_length=50, verbose_name='Тип татуировок'),
            preserve_default=False,
        ),
    ]
