# Generated by Django 5.0.6 on 2024-06-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_appointment_delete_appointmentv2'),
        ('site_setting', '0003_alter_aboutblock_description_alter_slider_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_setting.socialaccounticon', verbose_name='Иконка'),
        ),
    ]
