# Generated by Django 5.0.6 on 2024-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_master_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
