# Generated by Django 5.0.6 on 2024-05-13 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_master_tattoo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='description',
        ),
        migrations.AddField(
            model_name='works',
            name='type',
            field=models.CharField(default=1, max_length=30, verbose_name='Тип тату'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='MastersSocial/', verbose_name='Иконка')),
                ('link', models.CharField(max_length=150, verbose_name='Ссылка')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
