# Generated by Django 5.0.6 on 2024-05-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_appointment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=False, help_text='Мастер дал ответ клиенту', verbose_name='Ответил'),
        ),
    ]
