# Generated by Django 5.0.6 on 2024-05-17 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_slider_is_active'),
        ('site_setting', '0005_contact_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site_setting.salon'),
            preserve_default=False,
        ),
    ]
