# Generated by Django 5.0.6 on 2024-06-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='education',
        ),
        migrations.AddField(
            model_name='master',
            name='min_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Минимальная цена'),
        ),
    ]
