# Generated by Django 5.0.6 on 2024-06-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_master_education_master_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='short_description',
            field=models.TextField(blank=True, help_text='Текст отоброжаемый на странице со всеми мастерами', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='master',
            name='min_price',
            field=models.PositiveIntegerField(verbose_name='Минимальная цена'),
        ),
    ]
