# Generated by Django 5.0.6 on 2024-05-18 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_master_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.master'),
            preserve_default=False,
        ),
    ]
