# Generated by Django 5.0.6 on 2024-05-22 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_note_created_at'),
        ('site_setting', '0007_remove_aboutblock_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип тату')),
            ],
            options={
                'verbose_name': 'Тип тату',
                'verbose_name_plural': 'Типы тату',
            },
        ),
        migrations.AlterField(
            model_name='master',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_setting.salon', verbose_name='Салон'),
        ),
        migrations.RemoveField(
            model_name='master',
            name='tattoo_type',
        ),
        migrations.AddField(
            model_name='master',
            name='tattoo_type',
            field=models.ManyToManyField(blank=True, to='database.tattootype', verbose_name='Типы тату'),
        ),
    ]
