# Generated by Django 5.0.6 on 2024-05-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_session_is_active_alter_session_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='day_of_week',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20, verbose_name='День недели'),
        ),
    ]
