# Generated by Django 5.0.6 on 2024-05-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_alter_session_day_of_week'),
        ('site_setting', '0008_socialaccounticon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='site_setting.socialaccounticon'),
        ),
    ]
