# Generated by Django 5.0.6 on 2024-05-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_alter_socialaccount_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
    ]
