# Generated by Django 5.0.6 on 2024-05-28 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Site/AboutImages/', verbose_name='Картинка')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('short_description', models.TextField(help_text='Текст отоброжаемый на главной странице', verbose_name='Краткое описание')),
                ('description', models.TextField(help_text='текст используемый на подробной странице', verbose_name='Подробное описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название салона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('longitude', models.CharField(max_length=100, verbose_name='Долгота')),
                ('latitude', models.CharField(max_length=100, verbose_name='Широта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='SocialAccountIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='Site/SocialIcons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Социальная сеть иконка',
                'verbose_name_plural': 'Социальные сети иконки',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_setting.salon')),
            ],
        ),
        migrations.CreateModel(
            name='SalonSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(choices=[('vk', 'VK'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'Youtube'), ('twitter', 'Twitter'), ('whatsapp', 'Whatsapp')], max_length=20, verbose_name='Социальная сеть')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_setting.salon')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
