# Generated by Django 5.0.6 on 2024-05-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('short_description', models.TextField(help_text='Текст отоброжаемый на главной странице', verbose_name='Краткое описание')),
                ('description', models.TextField(help_text='текст используемый на подробной странице', verbose_name='Подробное описание')),
                ('icon', models.ImageField(help_text='Иконка на главной странице', upload_to='Site/AboutIcons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
