# Generated by Django 5.0.6 on 2024-06-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Slider/', verbose_name='Картинка')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отоброжать')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
            },
        ),
    ]
