# Generated by Django 5.0.6 on 2024-05-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0002_aboutblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutblock',
            name='image',
            field=models.ImageField(default=1, upload_to='Site/AboutImages/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
