# Generated by Django 5.0.6 on 2024-05-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0003_aboutblock_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название салона')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('longitude', models.CharField(max_length=100, verbose_name='Долгота')),
                ('latitude', models.CharField(max_length=100, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='longitude',
        ),
    ]
