# Generated by Django 5.0.6 on 2024-05-17 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0005_contact_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
