# Generated by Django 5.0.6 on 2024-05-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0006_salon_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutblock',
            name='icon',
        ),
    ]
