# Generated by Django 5.0.6 on 2024-05-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0007_remove_aboutblock_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccountIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='Site/SocialIcons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Социальная сеть иконка',
                'verbose_name_plural': 'Социальные сети иконки',
            },
        ),
    ]
