# Generated by Django 5.0.6 on 2024-05-24 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0008_socialaccounticon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(choices=[('VK', 'VK'), ('Telegram', 'Telegram'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Youtube', 'Youtube'), ('Twitter', 'Twitter'), ('Whatsapp', 'Whatsapp')], max_length=20, verbose_name='Социальная сеть')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_setting.salon')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
