# Generated by Django 5.0.6 on 2024-05-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0009_salonsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonsocial',
            name='social',
            field=models.CharField(choices=[('vk', 'VK'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'Youtube'), ('twitter', 'Twitter'), ('whatsapp', 'Whatsapp')], max_length=20, verbose_name='Социальная сеть'),
        ),
    ]
