# Generated by Django 5.0.6 on 2024-05-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
